### ISSUE TITLE
Meaningless error message?

### ISSUE THREAD

**Issue by holmanb** [nhorman/dropwatch#36] opened 2021-02-26 18:08 UTC
Perhaps this is a non-issue (if so, sorry for the noise), but I wanted to point out that if attempting to look up kernel symbols as a non-privileged  user, error messages (which are arguably useless) are interleaved with the output.  It looks like we could just add a check to see if `errno` is non-zero before doing that which would lead to cleaner output.  I'll submit a pull request in case that approach is acceptable. 

```
[bholman@coffee src]$ ./dropwatch -l kas
Initializing kallsyms db
dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
Error Scanning File: : Success
2 drops at location 0xffffffff96a76d79 [software]
```

**Comment by nhorman** [comment] 2021-02-26 19:11
Yeah, I think thats a bug in how I'm handling feof/ferror there.  Try this:
https://github.com/nhorman/dropwatch/tree/issue36
if you would please, and I'll commit it if the problem is rectified for you.

Thanks!

**Comment by holmanb** [comment] 2021-02-26 20:13
Thanks for the quick reply!  I just tested your changes @nhorman.  That works for me and is cleaner than my `errno` approach.  I'll close my pull request.

**Comment by nhorman** [comment] 2021-02-26 20:18
copy that, thank you for the quick turn around, I'll merge my change asap

**Comment by nhorman** [comment] 2021-02-26 20:18
fixed in https://github.com/nhorman/dropwatch/pull/38

**Closed by nhorman** 2021-02-26 20:18 UTC
